eval:
  dataset:
    num_classes: 5
  meta:
    batch_size: 20
  tasks:
    # Train.
    - set_name: train
      log_dir: eval/train/oracle_1shot
      config:
        name: supervised
        num_query_shots: 1
        num_support_shots: 1
        max_labeled_points: 1000
      sampler:
        name: uniform
        stratified: true
    - set_name: train
      log_dir: eval/train/oracle_5shot
      config:
        name: supervised
        num_query_shots: 1
        num_support_shots: 5
        max_labeled_points: 5000
      sampler:
        name: uniform
        stratified: true
    # Valid.
    - set_name: valid
      log_dir: eval/valid/oracle_1shot
      config:
        name: supervised
        num_query_shots: 1
        num_support_shots: 1
        max_labeled_points: 1000
      sampler:
        name: uniform
        stratified: true
    - set_name: valid
      log_dir: eval/valid/oracle_5shot
      config:
        name: supervised
        num_query_shots: 1
        num_support_shots: 5
        max_labeled_points: 5000
      sampler:
        name: uniform
        stratified: true
    # Test.
    - set_name: test
      log_dir: eval/test/oracle_1shot
      config:
        name: supervised
        num_query_shots: 1
        num_support_shots: 1
        max_labeled_points: 1000
      sampler:
        name: uniform
        stratified: true
    - set_name: test
      log_dir: eval/test/oracle_5shot
      config:
        name: supervised
        num_query_shots: 1
        num_support_shots: 5
        max_labeled_points: 5000
      sampler:
        name: uniform
        stratified: true
  repetitions: 1
  wait_time: 5
