data:
  name: omniglot
  read_config:
    data_dir: ???
    num_train_categories: 1000
    num_valid_categories: 200
    num_test_categories: 463
    shuffle: true
  build_config:
    shuffle: true

train:
  dataset:
    rotations: [0]
