# First-order MAML adaptation at training and test time.
meta_blocks:
  train:
    model:
      name: feed_forward
    adapt:
      name: maml
      first_order: true
      num_inner_steps: 5
      inner_optimizer:
        name: sgd
        learning_rate: 0.01
    optimizer:
      name: adam
      learning_rate: 0.001
  eval:
    model:
      name: feed_forward
    adapt:
      name: maml
      first_order: true
      num_inner_steps: 10
      inner_optimizer:
        name: sgd
        learning_rate: 0.01
