# Reptile adaptation at training and test time.
meta_blocks:
  train:
    model:
      name: feed_forward
    adapt:
      name: reptile
      batch_size: 10
      num_inner_steps: 8
      inner_optimizer:
        name: sgd
        learning_rate: 0.001
    optimizer:
      name: sgd
      learning_rate: 1.0
  eval:
    model:
      name: feed_forward
    adapt:
      name: reptile
      num_inner_steps: 50
      inner_optimizer:
        name: sgd
        learning_rate: 0.001
