language: python
python:
  - 3.6
  - 3.7
install:
  - pip install pytest-cov coveralls
  - pip install -r requirements/base.txt
  - pip install -e .
script:
  - py.test --cov-config .coveragerc --cov-report term-missing --cov=meta_blocks tests/
after_success:
  - coveralls
