adapt:
  name: reptile
  batch_size: 10
  inner_optimizer:
    name: sgd
    learning_rate: 0.0005

train:
  adapt:
    num_inner_steps: 10
  optimizer:
    name: sgd
    learning_rate: 1.0

eval:
  adapt:
    num_inner_steps: 50
