adapt:
  name: reptile
  batch_size: 50
  inner_optimizer:
    name: sgd
    learning_rate: 0.0005

model:
  name: embed_ff

train:
  adapt:
    num_inner_steps: 10
  optimizer:
    name: sgd
    learning_rate: 1.0

eval:
  adapt:
    num_inner_steps: 50
