defaults:
  # Defaults for job logging.
  - hydra/hydra_logging: colorlog
  - hydra/job_logging : colorlog
  # Experiment configuration.
  - experiment: ???
  - evaluation: ???
  - dataset: ???
  - model: ???
  - network: ???
  - adaptation: ???

run:
  seed: 1
