defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - experiment: ???
  - evaluation: ???
  - dataset: ???
  - model: ???
  - network: ???
  - adaptation: ???

run:
  seed: 1
