# Proto adaptation at training and test time.
meta_blocks:
  train:
    meta_dataset:
      batch_size: 2
      num_classes: 20
    model:
      name: proto
    adapt:
      name: proto
    optimizer:
      name: adam
      learning_rate: 0.001
      decay: 0.00025
    tasks:
      - set_name: train
        regime: 15shot
        log_dir: train
        config:
          name: classic_supervised
          num_query_shots: 15
          num_support_shots: 1
  eval:
    model:
      name: proto
    adapt:
      name: proto
