# Proto adaptation at training and test time.
meta_blocks:
  model:
    name: proto
    embedding_dim: 64
  train:
    adapt:
      name: proto
    optimizer:
      name: adam
      learning_rate: 0.002
  eval:
    adapt:
      name: proto
